{"name": "Тестируем ошибку входа с неправильными данными.", "status": "passed", "steps": [{"name": "POST запрос к /api/auth/login с данными {'email': 'savva1979@yandex.ru', 'password': 'DsRh0t@i7*'}", "status": "passed", "start": 1760501495331, "stop": 1760501495800}], "parameters": [{"name": "test_case_id", "value": "2"}], "start": 1760501495331, "stop": 1760501495803, "uuid": "03590954-c753-460c-b47f-bab1b3fff622", "historyId": "a2ddabbcc0cbb5f6cee07081069caa8f", "testCaseId": "e8f57114dc52a20f94d85eddecf030ca", "fullName": "tests.test_login_user.UserAuthenticationTests#test_login_user_wrong_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "UserAuthenticationTests"}, {"name": "host", "value": "DESKTOP-6FU1OQK"}, {"name": "thread", "value": "12712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}], "titlePath": ["tests", "test_login_user.py", "UserAuthenticationTests"]}