{"name": "Тестируем ошибку входа с неправильными данными.", "status": "passed", "steps": [{"name": "POST запрос к /api/auth/login с данными {'email': 'julibespalov@mail.ru', 'password': 'kcLi4jMnw7'}", "status": "passed", "start": 1760501894543, "stop": 1760501894995}], "parameters": [{"name": "test_case_id", "value": "2"}], "start": 1760501894543, "stop": 1760501894998, "uuid": "bc2872b2-2db8-4f51-baea-0c3773b09712", "historyId": "a2ddabbcc0cbb5f6cee07081069caa8f", "testCaseId": "e8f57114dc52a20f94d85eddecf030ca", "fullName": "tests.test_login_user.UserAuthenticationTests#test_login_user_wrong_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "UserAuthenticationTests"}, {"name": "host", "value": "DESKTOP-6FU1OQK"}, {"name": "thread", "value": "908-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}], "titlePath": ["tests", "test_login_user.py", "UserAuthenticationTests"]}